################################################################################
# Proxy points incoming traffic at ambassadors
################################################################################
nginxproxy:
  container_name: nginxproxy
  build: "https://github.com/fogies/docker-nginx.git#before-base"
  volumes:
    # nginx Config
    - "/localdata/scratch/config/nginxproxy:/config"
    # Certbot
    - "/localdata/scratch/secrets/certbot:/etc/letsencrypt"
    - "/localdata/scratch/secrets/certbotacme:/var/www/webroot"
    # DUB SSL Certificates (dub.washington.edu)
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.nginx.crt:/etc/ssl/nginx/dub.washington.edu.nginx.crt"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.key:/etc/ssl/nginx/dub.washington.edu.key"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.dhparams.pem:/etc/ssl/nginx/dub.washington.edu.dhparams.pem"
    # DUB SSL Certificates (dub.uw.edu)
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.nginx.crt:/etc/ssl/nginx/dub.uw.edu.nginx.crt"
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.key:/etc/ssl/nginx/dub.uw.edu.key"
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.dhparams.pem:/etc/ssl/nginx/dub.uw.edu.dhparams.pem"
    # DUBStaging Secrets
    - "/localdata/scratch/secrets/webdubstaging:/secrets/webdubstaging:ro"
  ports:
    - "80:80"
    - "443:443"
  links:
    - tt_tractdbcouchambassador:tt_tractdbcouch
    - tractdbpyramidambassador:tractdbpyramid
    - tractdbcouchambassador:tractdbcouch
    - tractdbwebambassador:tractdbweb
    - webdubambassador:webdub
    - webduboldpapersambassador:webduboldpapers
    - webdubstagingambassador:webdubstaging

################################################################################
# certbot, and its watcher
#
# sudo docker-compose -f docker-compose/docker-compose.yml run certbot certonly --webroot -w /var/www/webroot -d tractdb.org -d www.tractdb.org
# sudo openssl dhparam -out scratch/secrets/certbot/live/tractdb.org/dhparam.pem 2048
################################################################################
certbot:
  container_name: certbot
  image: certbot/certbot
  volumes:
    - "/localdata/scratch/secrets/certbot:/etc/letsencrypt"
    - "/localdata/scratch/secrets/certbotacme:/var/www/webroot"
  command: "renew"

certbotwatcher:
  container_name: certbotwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/certbot/certbot.git"
    SERVICE: "certbot"

################################################################################
# An old instance of tractdbcouch, left in place for TummyTrials deployment
################################################################################
tt_tractdbcouch:
  # port 5984
  container_name: tt_tractdbcouch
  build: "https://github.com/tractdb/docker-tractdb-couch.git"
  volumes:
    - "/localdata/backup/tt_tractdbcouch/data:/var/lib/couchdb"
    - "/localdata/backup/tt_tractdbcouch/logs:/var/log/couchdb"
    - "/localdata/scratch/secrets/tt_tractdbcouch:/secrets"

tt_tractdbcouchambassador:
  container_name: tt_tractdbcouchambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tt_tractdbcouch"

################################################################################
# tractdbcouch, its ambassador, and its watcher
################################################################################
tractdbcouch:
  # port 5984
  container_name: tractdbcouch
  build: "https://github.com/fogies/docker-couchdb.git"
  volumes:
    - "/localdata/backup/tractdbcouch/data:/var/lib/couchdb"
    - "/localdata/backup/tractdbcouch/logs:/var/log/couchdb"
    - "/localdata/scratch/secrets/tractdbcouch/secrets.yml:/docker-couchdb-secrets/secrets.yml:ro"

tractdbcouchambassador:
  container_name: tractdbcouchambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbcouch"

tractdbcouchwatcher:
  container_name: tractdbcouchwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/tractdb/docker-tractdb-couch.git"
    SERVICE: "tractdbcouch"

################################################################################
# tractdbpyramid, its ambassador, and its watcher
################################################################################
tractdbpyramid:
  # port 8080
  container_name: tractdbpyramid
  build: "https://github.com/fogies/docker-pyramid.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/tractdb-pyramid.git"
  volumes:
    - "/localdata/scratch/config/tractdbpyramid/pyramid_config.ini:/docker-pyramid-site/pyramid_config.production.ini:ro"
    - "/localdata/scratch/secrets/tractdbcouch/secrets.yml:/docker-pyramid-site/secrets_couchdb.yml:ro"
    - "/localdata/scratch/secrets/tractdbdarksky/secrets.yml:/docker-pyramid-site/secrets_darksky.yml:ro"
    - "/localdata/scratch/secrets/tractdbpyramid/secrets.yml:/docker-pyramid-site/secrets_pyramid.yml:ro"
    - "/localdata/scratch/secrets/tractdbstrava/secrets.yml:/docker-pyramid-site/secrets_strava.yml:ro"
  links:
    - tractdbcouchambassador:tractdbcouch

tractdbpyramidambassador:
  container_name: tractdbpyramidambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbpyramid"

tractdbpyramidwatcher:
  container_name: tractdbpyramidwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-pyramid.git"
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/tractdb-pyramid.git"
    SERVICE: "tractdbpyramid"

################################################################################
# tractdbweb, its ambassador, and its watcher
################################################################################
tractdbweb:
  # port 4000
  container_name: tractdbweb
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"

tractdbwebambassador:
  container_name: tractdbwebambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbweb"

tractdbwebwatcher:
  container_name: tractdbwebwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"
    SERVICE: "tractdbweb"

################################################################################
# webdub, its ambassador, and its watcher
################################################################################
webdub:
  # port 4000
  container_name: webdub
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"

webdubambassador:
  container_name: webdubambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name webdub"

webdubwatcher:
  container_name: webdubwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    SERVICE: "webdub"

################################################################################
# webdubstaging, its ambassador, and its watcher
################################################################################
webdubstaging:
  # port 4000
  container_name: webdubstaging
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    GIT_REPOSITORY_SITE_BRANCH: "people"

webdubstagingambassador:
  container_name: webdubstagingambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name webdubstaging"

webdubstagingwatcher:
  container_name: webdubstagingwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    SERVICE: "webdubstaging"

################################################################################
# webduboldpapers, its ambassador, and its watcher
################################################################################
webduboldpapers:
  # port 4000
  container_name: webduboldpapers
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"

webduboldpapersambassador:
  container_name: webduboldpapersambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name webduboldpapers"

webduboldpaperswatcher:
  container_name: webduboldpaperswatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"
    SERVICE: "webduboldpapers"

################################################################################
# webjayfo and its watcher
################################################################################
webjayfo:
  container_name: webjayfo
  build: "https://github.com/fogies/docker-jekyll-site.git"
  volumes:
    - "/localdata/scratch/config/webjayfo/publish_ssh.yml:/docker-jekyll-site/publish_ssh.yml"
    - "/localdata/scratch/secrets/barb.cs.washington.edu/publish_ssh_secrets.yml:/docker-jekyll-site/publish_ssh_secrets.yml"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"

webjayfowatcher:
  container_name: webjayfowatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"
    SERVICE: "webjayfo"

################################################################################
# webcse440 and its watcher
################################################################################
webcse440:
  container_name: webcse440
  build: "https://github.com/fogies/docker-jekyll-site.git"
  volumes:
    - "/localdata/scratch/config/webcse440/publish_ssh.yml:/docker-jekyll-site/publish_ssh.yml"
    - "/localdata/scratch/secrets/barb.cs.washington.edu/publish_ssh_secrets.yml:/docker-jekyll-site/publish_ssh_secrets.yml"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwcse440/web-cse440-sp17.git"

webcse440watcher:
  container_name: webcse440watcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwcse440/web-cse440-sp17.git"
    SERVICE: "webcse440"

################################################################################
# webcse510 and its watcher
################################################################################
webcse510:
  container_name: webcse510
  build: "https://github.com/fogies/docker-jekyll-site.git"
  volumes:
    - "/localdata/scratch/config/webcse510/publish_ssh.yml:/docker-jekyll-site/publish_ssh.yml"
    - "/localdata/scratch/secrets/barb.cs.washington.edu/publish_ssh_secrets.yml:/docker-jekyll-site/publish_ssh_secrets.yml"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwcse510/web-cse510-sp17.git"

webcse510watcher:
  container_name: webcse510watcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwcse510/web-cse510-sp17.git"
    SERVICE: "webcse510"
