################################################################################
# Proxy points incoming traffic at ambassadors
################################################################################
nginxproxy:
  build: "https://github.com/fogies/docker-nginx.git#before-base"
  volumes:
    # nginx Config
    - "/localdata/scratch/config/nginxproxy:/config"
    # DUB SSL Certificates
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.nginx.crt:/etc/ssl/nginx/dub.washington.edu.nginx.crt"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.key:/etc/ssl/nginx/dub.washington.edu.key"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.dhparams.pem:/etc/ssl/nginx/dub.washington.edu.dhparams.pem"
    # DUB staging password protection
    - "/localdata/scratch/secrets/webdubstaging:/secrets/webdubstaging"
    # TractDB SSL Certificates
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.nginx.crt:/etc/ssl/nginx/tractdb.org.nginx.crt"
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.key:/etc/ssl/nginx/tractdb.org.key"
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.dhparams.pem:/etc/ssl/nginx/tractdb.org.dhparams.pem"
  ports:
    - "80:80"
    - "443:443"
  links:
    - tractdbcouchambassador:tractdbcouch
    - tractdbpyramidambassador:tractdbpyramid
    - tractdbwebambassador:tractdbweb
    - webdubambassador:webdub
    - webduboldpapersambassador:webduboldpapers

################################################################################
# tractdbcouch, its ambassador, and its watcher
################################################################################
tractdbcouch:
  # port 5984
  build: "https://github.com/tractdb/docker-tractdb-couch.git"
  volumes:
    - "/localdata/backup/tractdbcouch/data:/var/lib/couchdb"
    - "/localdata/backup/tractdbcouch/logs:/var/log/couchdb"
    - "/localdata/scratch/secrets/tractdbcouch:/secrets"

tractdbcouchambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_tractdbcouch_1"

tractdbcouchwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/tractdb/docker-tractdb-couch.git"
    SERVICE: "tractdbcouch"

################################################################################
# tractdbpyramid, its ambassador, and its watcher
################################################################################
tractdbpyramid:
  # port 8080
  build: "https://github.com/tractdb/docker-tractdb-pyramid.git#before-base"
  volumes:
    - "/localdata/scratch/secrets/tractdbpyramid:/secrets"
  links:
    - tractdbcouchambassador:tractdbcouch

tractdbpyramidambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_tractdbpyramid_1"

tractdbpyramidwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/tractdb/docker-tractdb-pyramid.git"
    SERVICE: "tractdbpyramid"

################################################################################
# tractdbweb, its ambassador, and its watcher
################################################################################
tractdbweb:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"

tractdbwebambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_tractdbweb_1"

tractdbwebwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"
    SERVICE: "tractdbweb"

################################################################################
# webdub, its ambassador, and its watcher
################################################################################
webdub:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"

webdubambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_webdub_1"

webdubwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    SERVICE: "webdub"

################################################################################
# webduboldpapers, its ambassador, and its watcher
################################################################################
webduboldpapers:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"

webduboldpapersambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_webduboldpapers_1"

webduboldpaperswatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"
    SERVICE: "webduboldpapers"

################################################################################
# webjayfo and its watcher
################################################################################
webjayfo:
  build: "https://github.com/fogies/docker-jekyll-site.git"
  volumes:
    - "/localdata/scratch/secrets/webjayfo/webjayfo.yml:/publish.yml"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"

webjayfowatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"
    SERVICE: "webjayfo"
