################################################################################
# Proxy points incoming traffic at ambassadors
################################################################################
nginxproxy:
  build: "https://github.com/fogies/docker-nginx.git#before-base"
  volumes:
    # nginx Config
    - "/localdata/scratch/config/nginxproxy:/config"
    # DUB SSL Certificates (dub.washington.edu)
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.nginx.crt:/etc/ssl/nginx/dub.washington.edu.nginx.crt"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.key:/etc/ssl/nginx/dub.washington.edu.key"
    - "/localdata/scratch/secrets/dubssl/dub.washington.edu.dhparams.pem:/etc/ssl/nginx/dub.washington.edu.dhparams.pem"
    # DUB SSL Certificates (dub.uw.edu)
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.nginx.crt:/etc/ssl/nginx/dub.uw.edu.nginx.crt"
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.key:/etc/ssl/nginx/dub.uw.edu.key"
    - "/localdata/scratch/secrets/dubssl/dub.uw.edu.dhparams.pem:/etc/ssl/nginx/dub.uw.edu.dhparams.pem"
    # DUBStaging Secrets
    - "/localdata/scratch/secrets/webdubstaging:/secrets/webdubstaging:ro"
    # TractDB SSL Certificates
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.nginx.crt:/etc/ssl/nginx/tractdb.org.nginx.crt"
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.key:/etc/ssl/nginx/tractdb.org.key"
    - "/localdata/scratch/secrets/tractdbssl/tractdb.org.dhparams.pem:/etc/ssl/nginx/tractdb.org.dhparams.pem"
  ports:
    - "80:80"
    - "443:443"
  links:
    - tt_tractdbcouchambassador:tt_tractdbcouch
    - tractdbpyramidambassador:tractdbpyramid
    - tractdbcouchambassador:tractdbcouch
    - tractdbwebambassador:tractdbweb
    - webdubambassador:webdub
    - webduboldpapersambassador:webduboldpapers
    - webdubstagingambassador:webdubstaging


################################################################################
# An old instance of tractdbcouch, left in place for TummyTrials deployment
################################################################################
tt_tractdbcouch:
  # port 5984
  build: "https://github.com/tractdb/docker-tractdb-couch.git"
  volumes:
    - "/localdata/backup/tt_tractdbcouch/data:/var/lib/couchdb"
    - "/localdata/backup/tt_tractdbcouch/logs:/var/log/couchdb"
    - "/localdata/scratch/secrets/tt_tractdbcouch:/secrets"

tt_tractdbcouchambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_tt_tractdbcouch_1"

################################################################################
# tractdbcouch, its ambassador, and its watcher
################################################################################
tractdbcouch:
  # port 5984
  container_name: tractdbcouch
  build: "https://github.com/fogies/docker-couchdb.git"
  volumes:
    - "/localdata/backup/tractdbcouch/data:/var/lib/couchdb"
    - "/localdata/backup/tractdbcouch/logs:/var/log/couchdb"
    - "/localdata/scratch/secrets/tractdbcouch/secrets.yml:/docker-couchdb-secrets/secrets.yml:ro"

tractdbcouchambassador:
  container_name: tractdbcouchambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbcouch"

tractdbcouchwatcher:
  container_name: tractdbcouchwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/tractdb/docker-tractdb-couch.git"
    SERVICE: "tractdbcouch"

################################################################################
# tractdbpyramid, its ambassador, and its watcher
################################################################################
tractdbpyramid:
  # port 8080
  container_name: tractdbpyramid
  build: "https://github.com/fogies/docker-pyramid.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/tractdb-pyramid.git"
  volumes:
    - "/localdata/scratch/config/tractdbpyramid/pyramid_config.ini:/docker-pyramid-site/pyramid_config.production.ini:ro"
    - "/localdata/scratch/secrets/tractdbcouch/secrets.yml:/docker-pyramid-site/couchdb_secrets.yml:ro"
  links:
    - tractdbcouchambassador:tractdbcouch

tractdbpyramidambassador:
  container_name: tractdbpyramidambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbpyramid"

tractdbpyramidwatcher:
  container_name: tractdbpyramidwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-pyramid.git"
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/tractdb-pyramid.git"
    SERVICE: "tractdbpyramid"

################################################################################
# tractdbweb, its ambassador, and its watcher
################################################################################
tractdbweb:
  # port 4000
  container_name: tractdbweb
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"

tractdbwebambassador:
  container_name: tractdbwebambassador
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name tractdbweb"

tractdbwebwatcher:
  container_name: tractdbwebwatcher
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/tractdb/web-tractdb.git"
    SERVICE: "tractdbweb"

################################################################################
# webdub, its ambassador, and its watcher
################################################################################
webdub:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"

webdubambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_webdub_1"

webdubwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    SERVICE: "webdub"

################################################################################
# webdubstaging, its ambassador, and its watcher
################################################################################
webdubstaging:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    GIT_REPOSITORY_SITE_BRANCH: "people"

webdubstagingambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_webdubstaging_1"

webdubstagingwatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub.git"
    SERVICE: "webdubstaging"

################################################################################
# webduboldpapers, its ambassador, and its watcher
################################################################################
webduboldpapers:
  # port 4000
  build: "https://github.com/fogies/docker-jekyll-site.git"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"

webduboldpapersambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name dockercompose_webduboldpapers_1"

webduboldpaperswatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/uwdub/web-dub-oldpapers.git"
    SERVICE: "webduboldpapers"

################################################################################
# webjayfo and its watcher
################################################################################
webjayfo:
  build: "https://github.com/fogies/docker-jekyll-site.git#before-base"
  volumes:
    - "/localdata/scratch/secrets/webjayfo/webjayfo.yml:/publish.yml"
  environment:
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"

webjayfowatcher:
  build: "https://github.com/fogies/docker-watcher.git"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/slicer/docker-compose:/docker-compose"
  environment:
    GIT_REPOSITORY_SERVICE: "https://github.com/fogies/docker-jekyll-site.git"
    GIT_REPOSITORY_SITE: "https://github.com/fogies/web-jayfo.git"
    SERVICE: "webjayfo"
